### ISSUE TITLE
Search path for executables

### ISSUE THREAD

**Issue by stedolan** [ocurrent/bun#1]
My `afl-fuzz`, `afl-whatsup`, etc. live in `/usr/bin/`, not `/usr/local/bin`, and it's annoying to specify a bunch of arguments. I'd prefer if `bun` searched `$PATH` by default.

**Comment by yomimono** [comment]
`bos` handles that nicely but `spawn` doesn't (you're meant to use the higher-level and heavier `shexp` for stuff like that, I think); I'll change the defaults for `whatsup` and `gotcpu` in the meantime, so `PATH` resolution will handle them at least.

**Comment by yomimono** [comment]
fixed in 6cc7e2f6bf9cc19020ea698d5cd80fbdf102c1ca .
